/**
 * Protocol constants, frozen from the schema generated by Codex 0.154.0:
 *
 *   codex app-server generate-json-schema --out /tmp/proto
 *
 * Every string below was copied out of the generated schema (v2 bundle,
 * codex_app_server_protocol.v2.schemas.json plus ClientRequest.json).
 * Do not invent method names here; re-run the generator and update this file
 * when upgrading Codex. scripts/check-protocol.sh asserts they still exist.
 */

/** JSON-RPC protocol version spoken by codex app-server. */
export const JSONRPC_VERSION = '2.0';

/** Methods DSH sends to Codex. */
export const METHODS = {
  /** v1. params: { clientInfo: { name, title?, version } } */
  initialize: 'initialize',
  /** v2. params: { cwd?, model?, sandbox?, approvalPolicy?, ephemeral?, threadSource? } */
  threadStart: 'Thread/start',
  /** v2. params: { threadId, model?, cwd?, sandbox?, approvalPolicy?, excludeTurns? } */
  threadResume: 'Thread/resume',
  /** v2. params: { cwd?, limit?, cursor?, searchTerm?, archived?, sortKey?, sortDirection? } */
  threadList: 'Thread/list',
  /** v2. params: { threadId, includeTurns? } */
  threadRead: 'Thread/read',
  /** v2. params: { threadId, items } — raw Responses API items appended to history. */
  threadInjectItems: 'Thread/injectItems',
  /** v2. params: { threadId, input, cwd?, model?, effort?, summary?, outputSchema?, sandboxPolicy? } */
  turnStart: 'Turn/start',
  /** v2. params: { threadId, expectedTurnId, input, clientUserMessageId? } */
  turnSteer: 'Turn/steer',
  /** v2. params: { threadId, turnId } */
  turnInterrupt: 'Turn/interrupt',
};

/** Notifications DSH subscribes to (ServerNotification). All carry threadId. */
export const NOTIFICATIONS = {
  /** { threadId, turnId, itemId, delta } — streamed assistant text. */
  agentMessageDelta: 'Item/agentMessage/delta',
  /** { threadId, turnId, plan: [{ step, status }], explanation? } — the plan handoff. */
  planUpdated: 'Turn/plan/updated',
  /** { threadId, turn: { id, status, items, error? } } — end of one turn. */
  turnCompleted: 'Turn/completed',
  /** { threadId, ... } — queued-message set changed; basis for the discussion loop. */
  queueChanged: 'Thread/queue/changed',
  /** { threadId, turnId, plan } — plan delta stream. */
  planDelta: 'Item/plan/delta',
};

/** ServerRequest methods that ask the client for a decision. MVP rejects them. */
export const APPROVAL_REQUESTS = [
  'CommandExecutionRequestApproval',
  'FileChangeRequestApproval',
  'ApplyPatchApproval',
  'PermissionsRequestApproval',
  'McpServerElicitationRequest',
];

/** `Turn.status` values (v2 `Turn`). */
export const TURN_STATUS = ['inProgress', 'completed', 'interrupted', 'failed'];

/** `TurnPlanStep.status` values (v2 `TurnPlanStepStatus`). */
export const PLAN_STEP_STATUS = ['pending', 'inProgress', 'completed'];

/** Build the `UserInput[]` payload for Turn/start and Turn/steer. */
export function textInput(text) {
  return [{ type: 'text', text, text_elements: [] }];
}

/** Identify this client in the `initialize` handshake. */
export const CLIENT_INFO = {
  name: 'dsh-codex-bridge',
  title: 'DSH Codex Bridge',
  version: '0.1.0',
};

/** Default sandbox for bridge turns: planning never needs write access. */
export const DEFAULT_TURN_POLICY = {
  sandbox: 'read-only',
  approvalPolicy: 'never',
};
